const cleanerAll = 'https://localhost:7073/api/Cleaner/all'
const addOrder = 'https://localhost:7073/api/Order/add'
const allObjectUrl = 'https://localhost:7073/api/CleaningObject/all'
const allOrder = 'https://localhost:7073/api/Order/all'
const objectById = 'https://localhost:7073/api/CleaningObject/'
const autoselectUrl = 'https://localhost:7073/api/Cleaner/set/'